app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('auth/facebook', 'Auth\AuthController@redirectToProviderf');

Route::get('auth/facebook/callback', 'Auth\AuthController@handleProviderCallbackf');

Route::get('products/user/{id}', 'ProductController@allpost')->where('id', '[0-9]+');

Route::get('category/{cat}', 'ProductController@category');

Route::get('tag/{id}/products', 'ProductController@product_tag')->where('id', '[0-9]+');

Route::get('/', 'PrepaidController@lists');
//Route::get('/', 'ProductController@index');

Route::resource('products', 'ProductController',['except' => [
    'index'
]]);

Route::get('search', 'ProductController@getsearch');

Route::resource('tag', 'TagController');

Route::resource('page', 'PageController',['except' => [
    'index','create','destroy'
]]);



Route::group(['middleware' => 'auth'], function () {

    Route::get('user/{id}/products', 'ProductController@user_post')->where('id', '[0-9]+');

//    Route::get('product/{id}/purchase', 'PurchaseController@index')->where('id', '[0-9]+');

    Route::post('product/{id}/purchase', 'PurchaseController@index')->where('id', '[0-9]+');

    Route::get('product/{id}/sample', 'PurchaseController@sample')->where('id', '[0-9]+');

//    Route::get('product/{id}/specialpurchase', 'PurchaseController@special')->where('id', '[0-9]+');

    Route::post('product/{id}/specialpurchase', 'PurchaseController@special')->where('id', '[0-9]+');

    Route::get('mypurchases', 'PurchaseController@mypurchases');

    Route::get('prepaided/{id}', 'PurchaseController@prepaided');

    Route::get('user/sales', 'PurchaseController@user_sales');

    Route::get('user/purchases', 'PurchaseController@user_buys');

    Route::resource('profile', 'ProfileController');

    Route::resource('points', 'PointController');




    Route::group(['prefix' => 'messages'], function () {
        Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
        Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
        Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
        Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
        Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
        Route::delete('{id}', ['as' => 'messages.destroy', 'uses' => 'MessagesController@destroy']);
    });


});


Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::get('register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'RegistrationController@confirm'
]);


Route::group(['middleware' => 'admin'], function () {

    Route::resource('user', 'UserController', ['except' => [
        'create', 'store'
    ]]);
    Route::resource('admin', 'DashboardController', ['only' => ['index']]);

    Route::get('product/{id}/publish', 'ProductController@publish')->where('id', '[0-9]+');

    Route::get('commissions/{id}', 'PurchaseController@check_commissions');

    Route::resource('slider', 'SliderController');

    Route::get('published/products', 'DashboardController@publishedposts');

    Route::resource('prepaid', 'PrepaidController');

    Route::get('updatepoints', 'PointController@all');

    Route::get('sales', 'PurchaseController@sales');

});

Route::resource('spinwheel','SpinWheelController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{


    public function author()
    {
        return $this->belongsTo('App\User', "uploadby");
    }
    /**
     * Get the tags associated with the given posts.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany('App\Tag')->withTimestamps();
    }

    /**
     * Get a list of tag ids associated with the current post.
     *
     * @return array
     */

    public function getTagListAttribute()
    {
        return $this->tags->lists('id')->all();
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Slider;
use App\User;
use App\Tag;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;
use Intervention\Image\ImageManagerStatic as Image;
use App\Http\Requests;
use App\Http\Controllers\Controller;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'allpost', 'searchaction', 'category', 'product_tag']]);

    }

    public function index()
    {
        $product = Product::where('status', 1)
            ->orderBy('updated_at')
            ->paginate(20);

        $ebook = Product::where(config('type.Art&Ebooks'))->where('status', 1)->orderBy('updated_at', 'desc')->paginate(3);
        $mmovie = Product::where(config('type.Videos'))->where('status', 1)->orderBy('updated_at', 'desc')->paginate(3);
        $mmusic = Product::where(config('type.Audios'))->where('status', 1)->orderBy('updated_at', 'desc')->paginate(3);
        $tech = Product::where(config('type.Other'))->where('status', 1)->orderBy('updated_at', 'desc')->paginate(3);
        $msub = Product::where(config('type.MyanmarSubtitles'))->where('status', 1)->orderBy('updated_at', 'desc')->paginate(3);
        $ppcards = Product::where(config('type.PrepaidCards'))->where('status', 1)->orderBy('updated_at', 'desc')->paginate(3);
        $slider = Slider::all();

        return view('product.view')
            ->with('ebooks', $ebook)
            ->with('mmovies', $mmovie)
            ->with('mmusics', $mmusic)
            ->with('techs', $tech)
            ->with('msubs', $msub)
            ->with('ppcards', $ppcards)
            ->with('sliders', $slider);


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::orderBy('name')->lists('name', 'id');
        return view("product.create", compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\ProductRequest $request)
    {

        $products = new Product();
        $products->name = $request->input('name');
        $products->type = $request->input('type');
        $products->category = $request->input('category');
        $products->points = $request->input('points');
        $products->urls = $request->input('url');
        $products->other = $request->input('other');
        $products->uploadby = $request->user()->id;

        $this->validate($request, [
            'name' => 'required|max:255|unique:products',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'file' => 'required|mimes:jpeg,jpg,png,gif,svg,pdf,psd,mp3,mpga,wav,mid,midi,mp4,txt,srt,text,zip,apk,ttf',
            'sample' => 'mimes:jpeg,jpg,png,gif,svg,pdf,psd,mp3,mpga,wav,mid,midi,mp4,txt,srt,text,zip,apk,ttf',
        ]);

        Image::make(\Input::file('image'))->resize(260, 140)->save();
        $image = $request->file('image');
        $despath = 'uploads/images/';
        $filename = $image->getClientOriginalName();
        $image->move($despath, $filename);
        $products->media = $despath . $filename;


        $file = $request->file('file');
        $products->size = $file->getSize();
        $despath = 'uploads/files/';
        $filename = $file->getClientOriginalName();
        $file->move($despath, $filename);
        $products->file = $despath . $filename;

        if ($request->hasFile('sample')) {
            $sample = $request->file('sample');
            $despath = 'uploads/samples/';
            $samplename = $sample->getClientOriginalName();
            $sample->move($despath, $samplename);
            $products->sample = $despath . $samplename;
        }

        if ($request->user()->role == "admin") {
            $products->status = true;
        }
        $products->save();
        $tagsIds = $request->input('tag_list');
        /**
         * Add the lists of tags into the database.
         *
         */
        $products->tags()->attach($tagsIds);
        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);

        if ($product->status == false) {
            return redirect('/');
        }
        return view("product.show", compact('product'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        if($product->uploadby != Auth::user()->id)
        {
            return redirect('/');
        }
        $tags = Tag::orderBy('name')->lists('name', 'id');
        $taglists = $product->getTagListAttribute();
        return view('product.edit', compact('product', 'tags', 'taglists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        if($product->uploadby == Auth::user()->id)
        {
            $product->name = $request->input('name');
            $product->type = $request->input('type');
            $product->category = $request->input('category');
            $product->urls = $request->input('url');
            $product->other = $request->input('other');
            $product->points = $request->input('points');


            $this->validate($request, [
                'image' => 'image|mimes:jpeg,png,jpg,gif,svg',
                'file' => 'mimes:jpeg,jpg,png,gif,svg,pdf,psd,mp3,mpga,wav,mid,midi,mp4,txt,srt,text,zip,apk,ttf',
                'sample' => 'mimes:jpeg,jpg,png,gif,svg,pdf,psd,mp3,mpga,wav,mid,midi,mp4,txt,srt,text,zip,apk,ttf',
            ]);


            if ($request->hasFile('image')) {
                Image::make(\Input::file('image'))->resize(250, 140)->save();
                $file = $request->file('image');
                $despath = 'uploads/images/';
                $filename = $file->getClientOriginalName();
                $file->move($despath, $filename);
                $product->media = $despath . $filename;

            }


            if ($request->hasFile('file')) {
                $file = $request->file('file');
                $product->size = $file->getSize();
                $despath = 'uploads/files/';
                $filename = $file->getClientOriginalName();
                $file->move($despath, $filename);
                $product->file = $despath . $filename;
            }

            if ($request->hasFile('sample')) {
                $sample = $request->file('sample');
                $despath = 'uploads/samples/';
                $samplename = $sample->getClientOriginalName();
                $sample->move($despath, $samplename);
                $product->sample = $despath . $samplename;
            }

            if ($request->user()->role != "admin") {
                $product->status = false;
            }
            $product->save();
            $tagsIds = $request->input('tag_list');
            /**
             * Delete and Sync the list of tags into the database.
             *
             */
            if (is_null($tagsIds)) {
                $product->tags()->detach();
            } else {
                $product->tags()->sync($tagsIds);
            }

        }

        return redirect('/');


    }

    public function user_post(Request $request, $id)
    {
        $user = $request->user()->id;
        if ($id != $user) {
            return view("errors.503");
        }

        $products = Product::where('uploadby', $user)->orderBy('created_at', 'desc')->get();
        return view('product.ownpost')->with('products', $products)->with('users', $user);
    }

    public function allpost($id)
    {
        $user = User::find($id);
        $title = "Upload By";
        $products = Product::where('uploadby', $id)->where('status', 1)->orderBy('created_at', 'desc')->paginate(12);

        return view('product.uploadby')->with('products', $products)->with('user', $user)->with('title', $title);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */

    public function category($cat)
    {
        $product = Product::where('category', $cat)->where('status', 1)->orderBy('created_at', 'desc')->paginate(12);
        return view('category.cattag')
            ->with('products', $product)->with('cat', $cat);


    }

    public function destroy($id)
    {
        $product = Product::find($id);

        \File::delete(public_path($product->file));

        \File::delete(public_path($product->media));


        $product->delete();

        return redirect()->action("ProductController@user_post",[ Auth::id()]);
    }


    /**
     * Publishing the product.
     * @param  int $id
     */
    public function publish($id)
    {
        $product = Product::find($id);
        $product->status = true;
        $product->save();
        return redirect('admin');
    }

    public function getsearch(Request $request)
    {
        $search = $request->get('search');

        $products = Product::where('name', 'like', "%$search%")
            ->paginate(15)
            ->appends(['search' => $search]);
        return view('search_show')->with('products', $products);
    }

    public function product_tag($id)
    {
        $tag = Tag::find($id);

resources/views/product/commissions.blade.php
@extends('admin.theme')
@section('content')
    <h3>
        Commissions
    </h3>
    <div class="container">
        <table id="commission" class="display hover table">
            <thead>
            <tr>
                <th>Limit</th>
                <th>Commission</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>{{ "Grand Total"}}</th>
                <td>{{ $commission['total'] }}</td>
            </tr>
            <tr>
                <th>{{ "January"}}</th>
                <td>{{ $commission['jan'] }}</td>
            </tr>
            <tr>
                <th>{{ "February"}}</th>
                <td>{{ $commission['feb'] }}</td>
            </tr>
            <tr>
                <th>{{ "March"}}</th>
                <td>{{ $commission['mar'] }}</td>
            </tr>
            <tr>
                <th>{{ "April"}}</th>
                <td>{{ $commission['apr'] }}</td>
            </tr>
            <tr>
                <th>{{ "May"}}</th>
                <td>{{ $commission['may'] }}</td>
            </tr>
            <tr>
                <th>{{ "June"}}</th>
                <td>{{ $commission['jun'] }}</td>
            </tr>
            <tr>
                <th>{{ "July"}}</th>
                <td>{{ $commission['july'] }}</td>
            </tr>
            <tr>
                <th>{{ "August"}}</th>
                <td>{{ $commission['aug'] }}</td>
            </tr>
            <tr>
                <th>{{ "September"}}</th>
                <td>{{ $commission['sep'] }}</td>
            </tr>
            <tr>
                <th>{{ "October"}}</th>
                <td>{{ $commission['oct'] }}</td>
            </tr>
            <tr>
                <th>{{ "November"}}</th>
                <td>{{ $commission['nov'] }}</td>
            </tr>
            <tr>
                <th>{{ "December"}}</th>
                <td>{{ $commission['dec'] }}</td>
            </tr>
            </tbody>
        </table>
    </div>
@endsection

resources/views/product/create.blade.php
@extends('admin.theme')
@section('content')

    <h2>Customer Product Create </h2>

    <div class="container">
        @include('errors.list')

        <form action="/products" method="post" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">


            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control"  value="{{ old('name') }}" required="required">
            </div>

            <div class="form-group">
                <label for="type">Type</label>
                <select class="form-control input-sm" name="type" id="type">
                    @if(Auth::user()->role == 'admin')
                        @foreach(config('type.type') as $key=>$value)
                            <option value="{{$value}}">{{$value}}</option>
                        @endforeach
                    @else
                        @foreach(config('type.normaltype') as $key=>$value)
                            <option value="{{$value}}">{{$value}}</option>
                        @endforeach
                    @endif



                </select><!-- end of Item_Drop_Down -->
            </div>

            <div class="form-group">
                <label for="type">category</label>
                <select class="form-control input-sm" name="category" id="category" required="required">
                    <option value="">please select</option>
                    @foreach(config('type.all') as $key=>$value)
                        <option value="{{$value}}">{{$value}}</option>
                    @endforeach
                </select><!-- end of Item_Drop_Down -->
            </div>

            <div class="form-group">
                {!! Form::label('tag_list','Tags:') !!}
                {!! Form::select('tag_list[]',$tags,null,['id'=>'tag_list','class'=>'form-control','multiple']) !!}

            </div>

            <div class="form-group">


                <label for="Points">Points</label>
                <input type="number" name="points" id="points" class="form-control" value="{{ old('points') }}"/>

            </div>


            <div class="form-group">
                <label for="dec">Description</label>
                <textarea name='other'class="form-control" id="other">{{ old('other') }}</textarea>
                <p>Please use " &#60;br&#62; " for line spacing.</p>
            </div>


            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" name="url" id="url" class="form-control"  value="{{ old('url') }}" >
            </div>



            <form-group enctype="multipart/form-data">
                <label for="image">Preview Image</label>
                <input type="file" id="fileupload" name="image" required="required">
            </form-group>

            <form-group enctype="multipart/form-data">
                <label for="sample">Sample</label>
                <input type="file" id="sample" name="sample">
            </form-group>

            <form-group enctype="multipart/form-data">
                <label for="file">File</label>
                <input type="file" id="file" name="file" required="required">
            </form-group>
            <h4>Please Check <b>Category,Points,Image,File</b>.</h4>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Submit</button>
            </div>
        </form>


    </div>

@endsection

resources/views/product/edit.blade.php
@extends('admin.theme')
@section('content')

    <h2>Customer Edit </h2>

    <div class="container">
        @include('errors.list')
        <div class="col-md-9">
            <form action="{{route("products.update",$product->id)}}" method="post" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="PATCH" accept-charset="UTF-18">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control" value="{{$product->name}}" required="required">
                </div>
                <div class="form-group">
                    <label for="type">Type</label>
                    <select class="form-control input-sm" name="type" id="type">
                        @if(Auth::user()->role == 'admin')
                            @foreach(config('type.type') as $key=>$value)
                                <option value="{{$value}}"
                                    @if($value == $product->type)
                                    selected="selected"
                                    @endif
                                >{{$value}}</option>
                        @endforeach
                         @else
                              @foreach(config('type.normaltype') as $key=>$value)
                                    <option value="{{$value}}"
                                          @if($value == $product->type)
                                          selected="selected"
                                           @endif
                                    >{{$value}}</option>
                               @endforeach
                        @endif
                    </select>
                </div>

                <div class="form-group">
                    <label for="category">category</label>
                    <select class="form-control input-sm" name="category" id="category">

                        @foreach(config('type.all') as $key=>$value)
                            <option value="{{$value}}"
                                    @if($value == $product->category)
                                    selected="selected"
                                    @endif
                            >{{$value}}</option>
                        @endforeach
                    </select><!-- end of Item_Drop_Down -->
                </div>

                <div class="form-group">
                    {!! Form::label('tag_list','Tags:') !!}
                    {!! Form::select('tag_list[]',$tags,$taglists,['id'=>'tag_list','class'=>'form-control','multiple']) !!}

                </div>


                <div class="form-group">
                    <label for="Points">Points</label>
                    <input type="number" name="points" id="points" class="form-control" value="{{$product->points}}"/>
                </div>

                <div class="form-group">
                    <label for="dec">Description</label>
                    <textarea name='other' class="form-control" id="other">{{$product->other}}</textarea>
                    <p>Please use " &#60;br&#62; " for line spacing.</p>
                </div>

                <div class="form-group">
                    <label for="url">URL</label>
                    <input type="text" name="url" id="url" class="form-control"  value="{{ $product->urls }}" >
                </div>

                <form-group enctype="multipart/form-data">
                    <label for="image">Preview Image</label>
                    <input type="file" id="image" name="image">
                </form-group>

                <form-group enctype="multipart/form-data">
                    <label for="sample">Sample</label>
                    <input type="file" id="sample" name="sample">
                </form-group>

                <form-group enctype="multipart/form-data">
                    <label for="file">File</label>
                    <input type="file" id="file" name="file" >
                </form-group>

                <img src="{{asset($product->media) }}" class="img-responsive"/>

                {{--{{asset($product->file) }}--}}
                <h4>If you edit your products,you will have wait for admin's permission again to sale.</h4>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary form-control">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/product/lists.blade.php
@extends('theme')
@section('content')
    @include('info')
    <div class="container">
        @include('errors.list')
        @include('partials.flash')
        <div class="row">
            {{--@include('sidebar')--}}

            <div class="col-md-9">
                <div class="row" id="Container">
                    @for($i=0;$i<$ppcards->count();$i++)
                        <div class="col-lg-4 col-md-6 col-xs-12">
                            <div class="card ms-feature">
                                <div class="card-block text-center">
                                    <a href="{{url('products',$ppcards[$i]->id)}}">

                                        <img src="{{asset($ppcards[$i]->media) }}" alt="" class="img-responsive center-block">
                                    </a>
                                    <h4 class="text-normal text-center">
                                        {{ $ppcards[$i]->name }}
                                        {{--{{ str_limit($ppcards[$i]->name,20) }}--}}
                                    </h4>
                                    <div class="mt-2">
                      <span class="mr-2">
                          {{--<a href="{{ url('products/user/'.$ppcards[$i]->uploadby)}}">{{ $ppcards[$i]->author->name }}</a>--}}
                          Prep
                      </span>
                                        <span class="ms-tag ms-tag-success">
                                   {{ $ppcards[$i]->points }}
                                </span>
                                    </div>
                                    <a href="{{url('products',$ppcards[$i]->id)}}" class="btn btn-primary btn-sm btn-block btn-raised mt-2 no-mb">
                                        <i class="zmdi zmdi-shopping-cart-plus"></i>Claim</a>
                                </div>
                            </div>
                        </div>
                        @if($i % 3==2)
                            <div class="row" id="Container">
                                <img src="https://via.placeholder.com/1920x100.png" class="responsive">
                            </div>
                        @endif

                    @endfor
                </div>
            </div>


        </div>
    </div>

@endsection

resources/views/product/ownpost.blade.php
@extends('admin.theme')
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Upload By : {{ Auth::user()->name }}</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Point</th>
                                <th>Status</th>
                                <th>Operation Edit</th>
                                <th>Operation Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <td>{{ $product->id }}</td>
                                    <td>{{ $product->name }}</td>
                                    <td>{{ $product->points }}</td>
                                    @if($product->status == false)
                                        <td>{{ "Unpublished" }}</td>
                                    @else
                                        <td>{{ "Published" }}</td>
                                    @endif
                                    <td>
                                        <div class="form-group">
                                            <a type="button" class="btn btn-primary"
                                               href="{{ action('ProductController@edit', [$product->id] ) }}">Edit</a>
                                        </div>
                                    </td>
                                    <td>
                                        <form method="POST" action="{{ route("products.destroy", $product->id) }}" accept-charset="UTF-8">
                                            <input name="_method" type="hidden" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        </form>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>


@endsection

resources/views/product/purchase.blade.php
@extends("admin.theme")
@section("content")

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Purchase Data table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Seller</th>
                                <th>Product</th>
                                <th>Point</th>
                                <th>Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($buys as $buy)
                                <tr>
                                    @if(isset($buy->seller) )
                                        <td>{{ $buy->seller->name}}</td>
                                    @else
                                        <td>{{ $buy->seller_id }}</td>
                                    @endif
                                    <td>{{ $buy->product_name }}</td>
                                    <td>{{ $buy->getpoints + $buy->commission }}</td>
                                    <td>{{ $buy->created_at }}</td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </section>


@endsection