app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('auth/facebook', 'Auth\AuthController@redirectToProviderf');

Route::get('auth/facebook/callback', 'Auth\AuthController@handleProviderCallbackf');

Route::get('products/user/{id}', 'ProductController@allpost')->where('id', '[0-9]+');

Route::get('category/{cat}', 'ProductController@category');

Route::get('tag/{id}/products', 'ProductController@product_tag')->where('id', '[0-9]+');

Route::get('/', 'PrepaidController@lists');
//Route::get('/', 'ProductController@index');

Route::resource('products', 'ProductController',['except' => [
    'index'
]]);

Route::get('search', 'ProductController@getsearch');

Route::resource('tag', 'TagController');

Route::resource('page', 'PageController',['except' => [
    'index','create','destroy'
]]);



Route::group(['middleware' => 'auth'], function () {

    Route::get('user/{id}/products', 'ProductController@user_post')->where('id', '[0-9]+');

//    Route::get('product/{id}/purchase', 'PurchaseController@index')->where('id', '[0-9]+');

    Route::post('product/{id}/purchase', 'PurchaseController@index')->where('id', '[0-9]+');

    Route::get('product/{id}/sample', 'PurchaseController@sample')->where('id', '[0-9]+');

//    Route::get('product/{id}/specialpurchase', 'PurchaseController@special')->where('id', '[0-9]+');

    Route::post('product/{id}/specialpurchase', 'PurchaseController@special')->where('id', '[0-9]+');

    Route::get('mypurchases', 'PurchaseController@mypurchases');

    Route::get('prepaided/{id}', 'PurchaseController@prepaided');

    Route::get('user/sales', 'PurchaseController@user_sales');

    Route::get('user/purchases', 'PurchaseController@user_buys');

    Route::resource('profile', 'ProfileController');

    Route::resource('points', 'PointController');




    Route::group(['prefix' => 'messages'], function () {
        Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
        Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
        Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
        Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
        Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
        Route::delete('{id}', ['as' => 'messages.destroy', 'uses' => 'MessagesController@destroy']);
    });


});


Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::get('register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'RegistrationController@confirm'
]);


Route::group(['middleware' => 'admin'], function () {

    Route::resource('user', 'UserController', ['except' => [
        'create', 'store'
    ]]);
    Route::resource('admin', 'DashboardController', ['only' => ['index']]);

    Route::get('product/{id}/publish', 'ProductController@publish')->where('id', '[0-9]+');

    Route::get('commissions/{id}', 'PurchaseController@check_commissions');

    Route::resource('slider', 'SliderController');

    Route::get('published/products', 'DashboardController@publishedposts');

    Route::resource('prepaid', 'PrepaidController');

    Route::get('updatepoints', 'PointController@all');

    Route::get('sales', 'PurchaseController@sales');

});

Route::resource('spinwheel','SpinWheelController');

resources/views/admin/index.blade.php
@extends('admin.theme')
@section('content')


    <table id="example" class="display hover table" >
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>type</th>
            <th>category</th>
            <th>points</th>
            <th>Upload by</th>
            <th>File</th>
            <th>Size</th>
            <th>Publish</th>
            <th>Delete</th>



        </tr>
        </thead>
        <tbody class="table">
        @foreach($products as $product)
            <tr>

                <td>{{ $product->id }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->type }} </td>
                <td>{{ $product->category }}</td>
                <td>{{ $product->points }}</td>
                <td>{{$product->author->name}}</td>
                <td>{{explode("/",$product->file)[2]}}</td>
                <td>{{$product->size}}</td>


                <td>
                    <a class="btn btn-info btn-xs" href="{{action("ProductController@publish", [$product->id] )}}">Publish</a>
                </td>
                <td>
                    <form action="{{route("products.destroy",$product->id)}}" method="POST" accept-charset="UTF-8">
                        <input name="_method" type="hidden" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </td>




            </tr>
        @endforeach
        </tbody>
    </table>
    {!! $products->render() !!}
@endsection

resources/views/admin/index_old.blade.php
@extends('master')
@section('content')
    @foreach($products as $product)
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{asset($product->media) }}"  class="img-responsive" />


                </div>
                <div class="col-md-4">
                    {{ $product->type }} <br>
                    {{ $product->category }} <br>
                    {{ $product->points }} <br>
                    {{ $product->author->name }} <br>
                    {{ $product->size }} <br>
                </div>
                <div class="col-md-4">

                    <a class="btn btn-info btn-xs" href="{{action("ProductController@publish", [$product->id] )}}">Publish</a>
                    <a class="btn btn-info btn-xs" href="{{route("products.destroy",$product->id)}}">Delete</a>


                </div>
            </div>
            <br>
        </div>
    @endforeach
@endsection

resources/views/admin/mainframe_admin.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Marketplace For Anyone Who Wants to Buy and Sell  Digital Files">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Khit</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="images/favicon.png">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->
    <link rel="stylesheet" href="assets/custom.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.12/datatables.min.css"/>

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="assets/css/signin.css">
    <link rel="stylesheet" href="assets/css/custom.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.cyan-light_blue.min.css">
    <link rel="stylesheet" href="style.css">
    <link href="{{ asset('style.css') }}" rel="stylesheet">
    <link href="{{ asset('bootstrap.css') }}" rel="stylesheet">

    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.bootcss.com/admin-lte/2.3.5/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/admin-lte/2.3.5/js/app.min.js" type="text/javascript"></script>
    <script src='//cdn.tinymce.com/4/tinymce.min.js'></script>
    <script>
        tinymce.init({
            selector: ".mytextarea",
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
        });
    </script>
    <style>
        #messagehead{
            color: black;
        }
    </style>
</head>

<body class="skin-blue sidebar-mini">
<div class="wrapper">

@include('layout_admin.partials.mainheader')

@include('layout_admin.partials.sidebar')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

    @include('layout_admin.partials.contentheader')

    <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            @yield('content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @include('layout_admin.partials.controlsidebar')

    {{--@include('layouts.partials.footer')--}}

</div><!-- ./wrapper -->


{{--<div class="container" style="margin-top: -20px;">--}}


{{--<div class="container mdl-layout__content col-md-12">--}}
{{--@include('partials.flash')--}}

{{--@yield("content")--}}

{{--</div>--}}
{{--</div>--}}

</body>
</html>

resources/views/admin/published.blade.php
@extends('admin.theme')
@section('content')


    <table id="example" class="display hover table" >
        <thead>
        <tr>
            <th>ID</th>
            <th>type</th>
            <th>category</th>
            <th>points</th>
            <th>Upload by</th>
            <th>Size</th>
            <th>Delete</th>



        </tr>
        </thead>
        <tbody class="table">
        @foreach($products as $product)
            <tr>

                <td>{{ $product->id }}</td>
                <td>{{ $product->type }} </td>
                <td>{{ $product->category }}</td>
                <td>{{ $product->points }}</td>
                <td>{{$product->author->name}}</td>
                <td>{{$product->size}}</td>


                <td>
                    <form action="{{route("products.destroy",$product->id)}}" method="POST" accept-charset="UTF-8">
                        <input name="_method" type="hidden" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </td>




            </tr>
        @endforeach
        </tbody>
    </table>
    {!! $products->render() !!}
@endsection

resources/views/admin/slider_create.blade.php
@extends('admin.theme')
@section('content')
    <div class="container">

        <h2>Index Create</h2>
        @include('errors.list')

        <form action="/slider" method="post" enctype="multipart/form-data" >
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <form-group enctype="multipart/form-data" >
                <label for="size">Image</label>
                <input type="file" id="pathurl" name="pathurl">
            </form-group>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Submit</button>
            </div>
        </form>

    </div>
@endsection

resources/views/admin/slider_edit.blade.php
@extends('admin.theme')
@section('content')
    <div class="container">

        <h2>Index Create</h2>
        @include('errors.list')

        <form action="{{route("slider.update",$slider->id)}}" method="post" enctype="multipart/form-data" >
            <input type="hidden" name="_method" value="PATCH" accept-charset="UTF-18">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <form-group enctype="multipart/form-data" >
                <label for="size">Image</label>
                <input type="file" id="pathurl" name="pathurl">
            </form-group>
            <div class="form-group">
                <img src="{{asset($slider->pathurl) }}"  class="img-responsive" />
            </div>
            <div class="form-group">
                <label for="dec">Description</label>
                <textarea name='info'class="form-control" id="other">{{ old('info') }}</textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Submit</button>
            </div>
        </form>

    </div>
@endsection

resources/views/admin/slider_show.blade.php
@extends('admin.theme')
@section('content')
    <h2>Services admin view</h2>
    <table id="example" class="display hover table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Image</th>
            <th>Edit</th>
        </tr>
        </thead>
        <tbody class="table">
        @foreach($sliders as $slider)
            <tr>
                <td>{{ $slider->id }}</td>
                <td><img src="{{asset($slider->pathurl) }}" alt="" class="img-responsive"/></td>
                <td>
                    <a class="btn btn-info" href="{{route("slider.edit",$slider->id)}}">Edit</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection