app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('auth/facebook', 'Auth\AuthController@redirectToProviderf');

Route::get('auth/facebook/callback', 'Auth\AuthController@handleProviderCallbackf');

Route::get('products/user/{id}', 'ProductController@allpost')->where('id', '[0-9]+');

Route::get('category/{cat}', 'ProductController@category');

Route::get('tag/{id}/products', 'ProductController@product_tag')->where('id', '[0-9]+');

Route::get('/', 'PrepaidController@lists');
//Route::get('/', 'ProductController@index');

Route::resource('products', 'ProductController',['except' => [
    'index'
]]);

Route::get('search', 'ProductController@getsearch');

Route::resource('tag', 'TagController');

Route::resource('page', 'PageController',['except' => [
    'index','create','destroy'
]]);



Route::group(['middleware' => 'auth'], function () {

    Route::get('user/{id}/products', 'ProductController@user_post')->where('id', '[0-9]+');

//    Route::get('product/{id}/purchase', 'PurchaseController@index')->where('id', '[0-9]+');

    Route::post('product/{id}/purchase', 'PurchaseController@index')->where('id', '[0-9]+');

    Route::get('product/{id}/sample', 'PurchaseController@sample')->where('id', '[0-9]+');

//    Route::get('product/{id}/specialpurchase', 'PurchaseController@special')->where('id', '[0-9]+');

    Route::post('product/{id}/specialpurchase', 'PurchaseController@special')->where('id', '[0-9]+');

    Route::get('mypurchases', 'PurchaseController@mypurchases');

    Route::get('prepaided/{id}', 'PurchaseController@prepaided');

    Route::get('user/sales', 'PurchaseController@user_sales');

    Route::get('user/purchases', 'PurchaseController@user_buys');

    Route::resource('profile', 'ProfileController');

    Route::resource('points', 'PointController');




    Route::group(['prefix' => 'messages'], function () {
        Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
        Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
        Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
        Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
        Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
        Route::delete('{id}', ['as' => 'messages.destroy', 'uses' => 'MessagesController@destroy']);
    });


});


Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::get('register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'RegistrationController@confirm'
]);


Route::group(['middleware' => 'admin'], function () {

    Route::resource('user', 'UserController', ['except' => [
        'create', 'store'
    ]]);
    Route::resource('admin', 'DashboardController', ['only' => ['index']]);

    Route::get('product/{id}/publish', 'ProductController@publish')->where('id', '[0-9]+');

    Route::get('commissions/{id}', 'PurchaseController@check_commissions');

    Route::resource('slider', 'SliderController');

    Route::get('published/products', 'DashboardController@publishedposts');

    Route::resource('prepaid', 'PrepaidController');

    Route::get('updatepoints', 'PointController@all');

    Route::get('sales', 'PurchaseController@sales');

});

Route::resource('spinwheel','SpinWheelController');

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Cmgmyr\Messenger\Traits\Messagable;


class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword,Messagable;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password','active','activation_code','facebook_id','avatar'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
    

    public function posts()
    {

        return $this->hasMany('App\Product','uploadby');


    }

    public function updatepoints()
    {
        return $this->hasMany('App\Updatepoint');
    }

    public function sales()
    {
        return $this->hasMany('App\Purchase','seller_id');


    }

    public function buys()
    {
        return $this->hasMany('App\Purchase','buyer_id');

    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

use Auth;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'desc')->get();
        return view("user.index_data")
            ->with("users", $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $user = User::findorfail($id);
        $user->updatepoints = User::find($id)->updatepoints;
        return view("user.show", compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {

        $user = User::find($id);
        return view("user.edit")->with("user", $user);

    }

    public function editprofile($id)
    {
        $user = User::find($id);
        return view("user.user_profile_edit")->with("user", $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /**
         * Add the record to the updatepoint table.
         */
        $user = User::find($id);

        $points = $request->input('points');
        if ($points != "")
        {
            $admin_id = Auth::id();
            $user->updatepoints()->create([
                'admin_id' => $admin_id,
                'points' => $points
            ]);
            $user->points = $user->points + $points;
        }
        if ($user->role != "admin")
        {
            $role = $request->input('role');
            $user->role = $role;
        }   
        $user->save();
        return view("user.show", compact('user'));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user= User::find($id);
        $user->delete();
        $users = User::orderBy('id', 'desc')->get();;
        return view("user.index_data")
            ->with("users", $users);
    }

}

resources/views/user/edit.blade.php
@extends("admin.mainframe_admin")
@section("content")
    <div class="container">
        <div class="row">
            <div class="col-md-12"></div>
            <h2>Edit the Point of {{ $user->name }}</h2>
            @include('errors.list')
            <form action="{{ route("user.update", $user->id) }}" method="post">
                <input type="hidden" name="_method" value="PATCH">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                {{ $user->name }}
                {{ $user->description }}
                {{ $user->email }}

                <div class="form-group">
                    <label for="description">Point : </label>{{ $user->points }}
                    <input type="number" class="form-control" id="points" placeholder="Add positive or negative Point" name="points">
                </div>

                <div class="form-group">
                    <select class="form-control input-sm" name="role" id="role">
                        @foreach(config('type.usertype') as $key=>$value)
                            <option value="{{$value}}"
                            @if($value == $user->role)
                                selected="selected"
                            @endif
                                >{{$value}}</option>
                        @endforeach


                    </select><!-- end of Item_Drop_Down -->
                </div>

                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends("master")
@section("content")
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 align="center">All Posts</h1>

                @foreach($users as $user)
                    <h2><a href="{{ action('UserController@show', [$user->id] ) }}">{{ $user->name }}</a></h2>
                    <p>{{ $user->email }}</p>
                    <p>{{ $user->points }}</p>

                    <form method="POST" action="{{ route("user.destroy", $user->id) }}" accept-charset="UTF-8">
                        <a type="button" class="btn btn-primary" href="{{ action('UserController@edit', [$user->id] ) }}">Edit</a>
                        <input name="_method" type="hidden" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="submit" class="btn btn-default" value="Delete">
                    </form>
                    <hr>

                @endforeach
                {!! $users->render() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/user/index_data.blade.php
@extends("admin.theme")
@section("content")

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box"
                    <div class="box-header">
                        <h3 class="box-title">User Management</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>email</th>
                                <th>UserType</th>
                                <th>Joined Date</th>
                                <th>Operation Update</th>
                                <th>Operation Delete</th>


                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>

                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{$user->role}}</td>
                                    <td>{{$user->created_at->format('M d,Y ')}}</td>

                                    <td>
                                        <div class="form-group">
                                            <a type="button" class="btn btn-primary"
                                               href="{{ action('UserController@edit', [$user->id] ) }}">Update</a>
                                        </div>
                                    </td>
                                    <td>
                                        <form method="POST" action="{{ route("user.destroy", $user->id) }}" accept-charset="UTF-8">
                                            <input name="_method" type="hidden" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-danger delete" value="Delete">
                                        </form>
                                    </td>


                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                "pagingType": "full_numbers"
            });
            $(".delete").click(function(){
                if(confirm("Will you Delete this User?"))
                {
                    return true;
                }
                else{
                    return false;
                }
            });
        });
    </script>
@endsection

resources/views/user/profile_edit.blade.php
@extends("admin.theme")
@section("content")
    <div class="container">
        <div class="row">
            <form action="{{route("profile.update",$user->id)}}" method="POST" accept-charset="UTF-18">
                <input type="hidden" name="_method" value="PATCH" accept-charset="UTF-18">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter  Name"
                           value="{{$user->name}}">
                </div>
                <div class="form-group">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" id="address" name="address" placeholder="Enter  address"
                           value="{{$user->address}}">
                </div>
                <div class="form-group">
                    <label for="phoneno">Phone Number</label>
                    <input type="text" class="form-control" id="phoneno" name="phoneno" placeholder="Enter  phoneno"
                           value="{{$user->phoneno}}">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
                </div>
                <div class="form-group">
                    <label for="created_at">Join Khit:</label>
                    <label for="created_at">{{$user->created_at->format('M d,Y ')}}</label>

                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary form-control">Submit</button>
                </div>
            </form>
        </div>

    </div>
@endsection

resources/views/user/profile_show.blade.php
@extends("admin.theme")
@section("content")
    <div class="container">
        <div class="row">
            <h4>{{ $user->name }}</h4>

            <div class="col-md-6">
                <div class="form-group">
                    <h4><label for="name">Name:</label>
                        <label for="name">{{ $user->name }}</label></h4>

                </div>
                <div class="form-group">
                    <h4><label for="name">Email:</label>
                        <label for=arbname> {{ $user->email }}</label></h4>
                </div>
            </div>
            <div class="col-md-6">

            </div>
        </div>
        <a class="btn btn-info" href="{{route("profile.edit",$user->id)}}">Edit</a>
    </div>
@endsection

resources/views/user/show.blade.php
@extends("master")
@section("content")
    <div class="container">
        <div class="col-md-9">
        <div class="row">
            <div class="col-md-12">


                <h2>Name: {{ $user->name }}</h2>
                <h4>Email: {{ $user->email }}</h4>
                <h4>Points: {{ $user->points }}</h4>


                @unless ($user->updatepoints->isEmpty())
                    <h5>Points History</h5>
                    @foreach ($user->updatepoints as $updatepoint)

                        <h6>Points {{ $updatepoint->points }}</h6>
                        <h6>Time {{ $updatepoint->created_at }}</h6>

                    @endforeach

                @endunless


            </div>
        </div>
        <div class="col-md-4">
            @if(!Auth::guest() && Auth::user())
                <a class="btn btn-info btn-xs" href="{{route("user.edit",$user->id)}}">Edit</a>
            @endif
        </div>
        </div>
    </div>
@endsection

resources/views/user/user_profile_edit.blade.php
@extends("master")
@section("content")
    <div class="container" xmlns="http://www.w3.org/1999/html">
        <div class="row">
            <div class="col-md-12"></div>
            <h2>Edit the Profile of {{ $user->name }}</h2>
            @include('errors.list')
            <form action="{{ action('UserController@update', [$user->id] ) }}" method="POST" accept-charset="UTF-18">
                <input type="hidden" name="_method" value="PATCH">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                    <label for="title">name</label>
                    <input type="text" name="name" id="name" class="form-control" value="{{ $user->name }}"/>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>

        </form>
    </div>
@endsection