app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('auth/facebook', 'Auth\AuthController@redirectToProviderf');

Route::get('auth/facebook/callback', 'Auth\AuthController@handleProviderCallbackf');

Route::get('products/user/{id}', 'ProductController@allpost')->where('id', '[0-9]+');

Route::get('category/{cat}', 'ProductController@category');

Route::get('tag/{id}/products', 'ProductController@product_tag')->where('id', '[0-9]+');

Route::get('/', 'PrepaidController@lists');
//Route::get('/', 'ProductController@index');

Route::resource('products', 'ProductController',['except' => [
    'index'
]]);

Route::get('search', 'ProductController@getsearch');

Route::resource('tag', 'TagController');

Route::resource('page', 'PageController',['except' => [
    'index','create','destroy'
]]);



Route::group(['middleware' => 'auth'], function () {

    Route::get('user/{id}/products', 'ProductController@user_post')->where('id', '[0-9]+');

//    Route::get('product/{id}/purchase', 'PurchaseController@index')->where('id', '[0-9]+');

    Route::post('product/{id}/purchase', 'PurchaseController@index')->where('id', '[0-9]+');

    Route::get('product/{id}/sample', 'PurchaseController@sample')->where('id', '[0-9]+');

//    Route::get('product/{id}/specialpurchase', 'PurchaseController@special')->where('id', '[0-9]+');

    Route::post('product/{id}/specialpurchase', 'PurchaseController@special')->where('id', '[0-9]+');

    Route::get('mypurchases', 'PurchaseController@mypurchases');

    Route::get('prepaided/{id}', 'PurchaseController@prepaided');

    Route::get('user/sales', 'PurchaseController@user_sales');

    Route::get('user/purchases', 'PurchaseController@user_buys');

    Route::resource('profile', 'ProfileController');

    Route::resource('points', 'PointController');




    Route::group(['prefix' => 'messages'], function () {
        Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
        Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
        Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
        Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
        Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
        Route::delete('{id}', ['as' => 'messages.destroy', 'uses' => 'MessagesController@destroy']);
    });


});


Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::get('register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'RegistrationController@confirm'
]);


Route::group(['middleware' => 'admin'], function () {

    Route::resource('user', 'UserController', ['except' => [
        'create', 'store'
    ]]);
    Route::resource('admin', 'DashboardController', ['only' => ['index']]);

    Route::get('product/{id}/publish', 'ProductController@publish')->where('id', '[0-9]+');

    Route::get('commissions/{id}', 'PurchaseController@check_commissions');

    Route::resource('slider', 'SliderController');

    Route::get('published/products', 'DashboardController@publishedposts');

    Route::resource('prepaid', 'PrepaidController');

    Route::get('updatepoints', 'PointController@all');

    Route::get('sales', 'PurchaseController@sales');

});

Route::resource('spinwheel','SpinWheelController');

app/Prepaid.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Prepaid extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

}

app/Http/Controllers/PrepaidController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use App\Prepaid;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Intervention\Image\ImageManagerStatic as Image;
use Illuminate\Support\Facades\File;

class PrepaidController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cards = Prepaid::orderBy('id', 'desc')->paginate(20);
        return view("prepaid.index",compact('cards'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cards = Prepaid::all()->groupBy('type');
        return view("prepaid.create",compact('cards'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newcard = new Prepaid();
        $newcard->type = $request->input('type');
        $newcard->remark = $request->input('remark');
        Image::make(\Input::file('image'))->resize(260, 140)->save();
        $image = $request->file('image');
        $despath = 'uploads/images/';
        $filename = $image->getClientOriginalName();
        $image->move($despath, $filename);
        $newcard->file = $despath . $filename;
        /*
         * Sample
         */
        if ($request->hasFile('sample')) {
            Image::make(\Input::file('sample'))->resize(260, 140)->save();
            $sample = $request->file('sample');
            $samplename = $sample->getClientOriginalName();
            $sample->move($despath, $samplename);
            $newcard->sample = $despath . $samplename;
        }
        $newcard->save();
        return redirect('prepaid/create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $prepaid = Prepaid::find($id);
        $prepaid->forceDelete();
        return redirect('prepaid');
    }

    public function lists()
    {
        $ppcards = Product::where(config('type.PrepaidCards'))->where('status', 1)->get();
        return view('product.lists',compact('ppcards'));

    }
}

resources/views/prepaid/create.blade.php
@extends('admin.theme')
@section('content')

    <h2>Prepaid</h2>
    @foreach($cards as $key => $value)
        <b>{{ $value->count() }}</b>
        {{ $value[0]->type  }}
        <br>
     @endforeach

    <div class="container">
        @include('errors.list')

        <form action="{{action('PrepaidController@store')}}" method="post" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <div class="form-group">
                <label for="type">Type</label>
                <select class="form-control input-sm" name="type" id="type">
                    @if(Auth::user()->role == 'admin')
                        @foreach(config('type.prepaid') as $key=>$value)
                            <option value="{{$value}}">{{$value}}</option>
                        @endforeach
                    @endif
                </select><!-- end of Item_Drop_Down -->
            </div>

            <form-group enctype="multipart/form-data">
                <label for="image">Image</label>
                <input type="file" id="image" name="image" required="required">
            </form-group>

            <form-group enctype="multipart/form-data">
                <label for="image">Preview</label>
                <input type="file" id="sample" name="sample">
            </form-group>

            <div class="form-group">
                <label for="remark">Remark</label>
                <textarea name='remark'class="form-control" id="remark">{{ old('remark') }}</textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Submit</button>
            </div>
        </form>


    </div>
@endsection

resources/views/prepaid/index.blade.php
@extends('admin.theme')
@section('content')
    <h3>
        Prepaid
    </h3>
    <div class="container">
        <table id="example" class="display hover table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Type</th>
                <th>Remark</th>
                <th>Created At</th>
                <th>Operation Delete</th>
            </tr>
            </thead>
            <tbody>
            @foreach($cards as $card)
                <tr>
                    <td>{{ $card->id }}</td>
                    <td>{{ $card->type }}</td>
                    <td>{{ $card->remark }}</td>
                     <td>{{ $card->created_at }}</td>
                    <td>
                        <form method="POST" action="{{ route("prepaid.destroy", $card->id) }}" accept-charset="UTF-8">
                            <input name="_method" type="hidden" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </td>

                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                {!! $cards->render() !!}
            </ul>
        </div>
    </div>
@endsection